---
- name: install required dependencies
  apt:
    name: git
    state: present
    update_cache: yes

- name: clone aiolegomac
  git:
    repo: https://github.com/beenje/aiolegomac.git
    dest: /home/pi/aiolegomac

- name: build aiolegomac image
  docker_image:
    path: /home/pi/aiolegomac
    name: "{{ aiolegomac_image }}"
    state: present

- name: build pigpiod image
  docker_image:
    path: /home/pi/aiolegomac/pigpiod
    name: "{{ pigpiod_image }}"
    state: present
