---
- name: install requirements
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-docker
    state: present

- name: import docker repo gpg key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    id: 0EBFCD88
    state: present

- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian/ {{ ansible_distribution_release }} stable
    state: present
    filename: docker-raspbian

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    install_recommends: false
    update_cache: yes

- name: add pi user to the docker group
  user:
    name: pi
    groups: docker
    append: yes
